//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public Nullable<double> Contact { get; set; }
        public string Email { get; set; }

        
              
            }
        }
